<?php

use Illuminate\Database\Seeder;
use App\CountryCodes;
class CountryCodeTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
       $countries =[
        [
          "iso" => "AF",
          "name_caps" => "AFGHANISTAN",
          "name" => "Afghanistan",
          "iso3" => "AFG",
          "numcode" => 4,
          "phonecode" => 93,
        ],
        [
          "iso" => "AL",
          "name_caps" => "ALBANIA",
          "name" => "Albania",
          "iso3" => "ALB",
          "numcode" => 8,
          "phonecode" => 355,
        ],
        [
          "iso" => "DZ",
          "name_caps" => "ALGERIA",
          "name" => "Algeria",
          "iso3" => "DZA",
          "numcode" => 12,
          "phonecode" => 213,
        ],
        [
          "iso" => "AS",
          "name_caps" => "AMERICAN SAMOA",
          "name" => "American Samoa",
          "iso3" => "ASM",
          "numcode" => 16,
          "phonecode" => 1684,
        ],
        [
          "iso" => "AD",
          "name_caps" => "ANDORRA",
          "name" => "Andorra",
          "iso3" => "AND",
          "numcode" => 20,
          "phonecode" => 376,
        ],
        [
          "iso" => "AO",
          "name_caps" => "ANGOLA",
          "name" => "Angola",
          "iso3" => "AGO",
          "numcode" => 24,
          "phonecode" => 244,
        ],
        [
          "iso" => "AI",
          "name_caps" => "ANGUILLA",
          "name" => "Anguilla",
          "iso3" => "AIA",
          "numcode" => 660,
          "phonecode" => 1264,
        ],
        [
          "iso" => "AQ",
          "name_caps" => "ANTARCTICA",
          "name" => "Antarctica",
          "iso3" => null,
          "numcode" => null,
          "phonecode" => 0,
        ],
        [
          "iso" => "AG",
          "name_caps" => "ANTIGUA AND BARBUDA",
          "name" => "Antigua and Barbuda",
          "iso3" => "ATG",
          "numcode" => 28,
          "phonecode" => 1268,
        ],
        [
          "iso" => "AR",
          "name_caps" => "ARGENTINA",
          "name" => "Argentina",
          "iso3" => "ARG",
          "numcode" => 32,
          "phonecode" => 54,
        ],
   [
          "iso" => "AM",
          "name_caps" => "ARMENIA",
          "name" => "Armenia",
          "iso3" => "ARM",
          "numcode" => 51,
          "phonecode" => 374,
        ],
        [
          "iso" => "AW",
          "name_caps" => "ARUBA",
          "name" => "Aruba",
          "iso3" => "ABW",
          "numcode" => 533,
          "phonecode" => 297,
        ],
        [
          "iso" => "AU",
          "name_caps" => "AUSTRALIA",
          "name" => "Australia",
          "iso3" => "AUS",
          "numcode" => 36,
          "phonecode" => 61,
        ],
        [
          "iso" => "AT",
          "name_caps" => "AUSTRIA",
          "name" => "Austria",
          "iso3" => "AUT",
          "numcode" => 40,
          "phonecode" => 43,
        ],
        [
          "iso" => "AZ",
          "name_caps" => "AZERBAIJAN",
          "name" => "Azerbaijan",
          "iso3" => "AZE",
          "numcode" => 31,
          "phonecode" => 994,
        ],
        [
          "iso" => "BS",
          "name_caps" => "BAHAMAS",
          "name" => "Bahamas",
          "iso3" => "BHS",
          "numcode" => 44,
          "phonecode" => 1242,
        ],
        [
          "iso" => "BH",
          "name_caps" => "BAHRAIN",
          "name" => "Bahrain",
          "iso3" => "BHR",
          "numcode" => 48,
          "phonecode" => 973,
        ],
        [
          "iso" => "BD",
          "name_caps" => "BANGLADESH",
          "name" => "Bangladesh",
          "iso3" => "BGD",
          "numcode" => 50,
          "phonecode" => 880,
        ],
        [
          "iso" => "BB",
          "name_caps" => "BARBADOS",
          "name" => "Barbados",
          "iso3" => "BRB",
          "numcode" => 52,
          "phonecode" => 1246,
        ],
        [
          "iso" => "BY",
          "name_caps" => "BELARUS",
          "name" => "Belarus",
          "iso3" => "BLR",
          "numcode" => 112,
          "phonecode" => 375,
        ],
        [
          "iso" => "BE",
          "name_caps" => "BELGIUM",
          "name" => "Belgium",
          "iso3" => "BEL",
          "numcode" => 56,
          "phonecode" => 32,
        ],
        [
          "iso" => "BZ",
          "name_caps" => "BELIZE",
          "name" => "Belize",
          "iso3" => "BLZ",
          "numcode" => 84,
          "phonecode" => 501,
        ],
        [
          "iso" => "BJ",
          "name_caps" => "BENIN",
          "name" => "Benin",
          "iso3" => "BEN",
          "numcode" => 204,
          "phonecode" => 229,
        ],
        [
          "iso" => "BM",
          "name_caps" => "BERMUDA",
          "name" => "Bermuda",
          "iso3" => "BMU",
          "numcode" => 60,
          "phonecode" => 1441,
        ],
        [
          "iso" => "BT",
          "name_caps" => "BHUTAN",
          "name" => "Bhutan",
          "iso3" => "BTN",
          "numcode" => 64,
          "phonecode" => 975,
        ],
        [
          "iso" => "BO",
          "name_caps" => "BOLIVIA",
          "name" => "Bolivia",
          "iso3" => "BOL",
          "numcode" => 68,
          "phonecode" => 591,
        ],
        [
          "iso" => "BA",
          "name_caps" => "BOSNIA AND HERZEGOVINA",
          "name" => "Bosnia and Herzegovina",
          "iso3" => "BIH",
          "numcode" => 70,
          "phonecode" => 387,
        ],
        [
          "iso" => "BW",
          "name_caps" => "BOTSWANA",
          "name" => "Botswana",
          "iso3" => "BWA",
          "numcode" => 72,
          "phonecode" => 267,
        ],
        [
          "iso" => "BV",
          "name_caps" => "BOUVET ISLAND",
          "name" => "Bouvet Island",
          "iso3" => null,
          "numcode" => null,
          "phonecode" => 0,
        ],
        [
          "iso" => "BR",
          "name_caps" => "BRAZIL",
          "name" => "Brazil",
          "iso3" => "BRA",
          "numcode" => 76,
          "phonecode" => 55,
        ],
        [
          "iso" => "IO",
          "name_caps" => "BRITISH INDIAN OCEAN TERRITORY",
          "name" => "British Indian Ocean Territory",
          "iso3" => null,
          "numcode" => null,
          "phonecode" => 246,
        ],
        [
          "iso" => "BN",
          "name_caps" => "BRUNEI DARUSSALAM",
          "name" => "Brunei Darussalam",
          "iso3" => "BRN",
          "numcode" => 96,
          "phonecode" => 673,
        ],
        [
          "iso" => "BG",
          "name_caps" => "BULGARIA",
          "name" => "Bulgaria",
          "iso3" => "BGR",
          "numcode" => 100,
          "phonecode" => 359,
        ],
        [
          "iso" => "BF",
          "name_caps" => "BURKINA FASO",
          "name" => "Burkina Faso",
          "iso3" => "BFA",
          "numcode" => 854,
          "phonecode" => 226,
        ],
        [
          "iso" => "BI",
          "name_caps" => "BURUNDI",
          "name" => "Burundi",
          "iso3" => "BDI",
          "numcode" => 108,
          "phonecode" => 257,
        ],
        [
          "iso" => "KH",
          "name_caps" => "CAMBODIA",
          "name" => "Cambodia",
          "iso3" => "KHM",
          "numcode" => 116,
          "phonecode" => 855,
        ],
        [
          "iso" => "CM",
          "name_caps" => "CAMEROON",
          "name" => "Cameroon",
          "iso3" => "CMR",
          "numcode" => 120,
          "phonecode" => 237,
        ],
        [
          "iso" => "CA",
          "name_caps" => "CANADA",
          "name" => "Canada",
          "iso3" => "CAN",
          "numcode" => 124,
          "phonecode" => 1,
        ],
        [
          "iso" => "CV",
          "name_caps" => "CAPE VERDE",
          "name" => "Cape Verde",
          "iso3" => "CPV",
          "numcode" => 132,
          "phonecode" => 238,
        ],
        [
          "iso" => "KY",
          "name_caps" => "CAYMAN ISLANDS",
          "name" => "Cayman Islands",
          "iso3" => "CYM",
          "numcode" => 136,
          "phonecode" => 1345,
        ],
        [
          "iso" => "CF",
          "name_caps" => "CENTRAL AFRICAN REPUBLIC",
          "name" => "Central African Republic",
          "iso3" => "CAF",
          "numcode" => 140,
          "phonecode" => 236,
        ],
        [
          "iso" => "TD",
          "name_caps" => "CHAD",
          "name" => "Chad",
          "iso3" => "TCD",
          "numcode" => 148,
          "phonecode" => 235,
        ],
        [
          "iso" => "CL",
          "name_caps" => "CHILE",
          "name" => "Chile",
          "iso3" => "CHL",
          "numcode" => 152,
          "phonecode" => 56,
        ],
        [
          "iso" => "CN",
          "name_caps" => "CHINA",
          "name" => "China",
          "iso3" => "CHN",
          "numcode" => 156,
          "phonecode" => 86,
        ],
        [
          "iso" => "CX",
          "name_caps" => "CHRISTMAS ISLAND",
          "name" => "Christmas Island",
          "iso3" => null,
          "numcode" => null,
          "phonecode" => 61,
        ],
        [
          "iso" => "CC",
          "name_caps" => "COCOS (KEELING) ISLANDS",
          "name" => "Cocos (Keeling) Islands",
          "iso3" => null,
          "numcode" => null,
          "phonecode" => 672,
        ],
        [
          "iso" => "CO",
          "name_caps" => "COLOMBIA",
          "name" => "Colombia",
          "iso3" => "COL",
          "numcode" => 170,
          "phonecode" => 57,
        ],
        [
          "iso" => "KM",
          "name_caps" => "COMOROS",
          "name" => "Comoros",
          "iso3" => "COM",
          "numcode" => 174,
          "phonecode" => 269,
        ],
        [
          "iso" => "CG",
          "name_caps" => "CONGO",
          "name" => "Congo",
          "iso3" => "COG",
          "numcode" => 178,
          "phonecode" => 242,
        ],
        [
          "iso" => "CD",
          "name_caps" => "CONGO, THE DEMOCRATIC REPUBLIC OF THE",
          "name" => "Congo, the Democratic Republic of the",
          "iso3" => "COD",
          "numcode" => 180,
          "phonecode" => 242,
        ],
      [
          "iso" => "CK",
          "name_caps" => "COOK ISLANDS",
          "name" => "Cook Islands",
          "iso3" => "COK",
          "numcode" => 184,
          "phonecode" => 682,
        ],
        [
          "iso" => "CR",
          "name_caps" => "COSTA RICA",
          "name" => "Costa Rica",
          "iso3" => "CRI",
          "numcode" => 188,
          "phonecode" => 506,
        ],
        [
          "iso" => "CI",
          "name_caps" => "COTE D'IVOIRE",
          "name" => "Cote D'Ivoire",
          "iso3" => "CIV",
          "numcode" => 384,
          "phonecode" => 225,
        ],
        [
          "iso" => "HR",
          "name_caps" => "CROATIA",
          "name" => "Croatia",
          "iso3" => "HRV",
          "numcode" => 191,
          "phonecode" => 385,
        ],
        [
          "iso" => "CU",
          "name_caps" => "CUBA",
          "name" => "Cuba",
          "iso3" => "CUB",
          "numcode" => 192,
          "phonecode" => 53,
        ],
        [
          "iso" => "CY",
          "name_caps" => "CYPRUS",
          "name" => "Cyprus",
          "iso3" => "CYP",
          "numcode" => 196,
          "phonecode" => 357,
        ],
        [
          "iso" => "CZ",
          "name_caps" => "CZECH REPUBLIC",
          "name" => "Czech Republic",
          "iso3" => "CZE",
          "numcode" => 203,
          "phonecode" => 420,
        ],
        [
          "iso" => "DK",
          "name_caps" => "DENMARK",
          "name" => "Denmark",
          "iso3" => "DNK",
          "numcode" => 208,
          "phonecode" => 45,
        ],
        [
          "iso" => "DJ",
          "name_caps" => "DJIBOUTI",
          "name" => "Djibouti",
          "iso3" => "DJI",
          "numcode" => 262,
          "phonecode" => 253,
        ],
        [
          "iso" => "DM",
          "name_caps" => "DOMINICA",
          "name" => "Dominica",
          "iso3" => "DMA",
          "numcode" => 212,
          "phonecode" => 1767,
        ],
        [
          "iso" => "DO",
          "name_caps" => "DOMINICAN REPUBLIC",
          "name" => "Dominican Republic",
          "iso3" => "DOM",
          "numcode" => 214,
          "phonecode" => 1809,
        ],
        [
          "iso" => "EC",
          "name_caps" => "ECUADOR",
          "name" => "Ecuador",
          "iso3" => "ECU",
          "numcode" => 218,
          "phonecode" => 593,
        ],
        [
          "iso" => "EG",
          "name_caps" => "EGYPT",
          "name" => "Egypt",
          "iso3" => "EGY",
          "numcode" => 818,
          "phonecode" => 20,
        ],
        [
          "iso" => "SV",
          "name_caps" => "EL SALVADOR",
          "name" => "El Salvador",
          "iso3" => "SLV",
          "numcode" => 222,
          "phonecode" => 503,
        ],
        [
          "iso" => "GQ",
          "name_caps" => "EQUATORIAL GUINEA",
          "name" => "Equatorial Guinea",
          "iso3" => "GNQ",
          "numcode" => 226,
          "phonecode" => 240,
        ],
        [
          "iso" => "ER",
          "name_caps" => "ERITREA",
          "name" => "Eritrea",
          "iso3" => "ERI",
          "numcode" => 232,
          "phonecode" => 291,
        ],
        [
          "iso" => "EE",
          "name_caps" => "ESTONIA",
          "name" => "Estonia",
          "iso3" => "EST",
          "numcode" => 233,
          "phonecode" => 372,
        ],
        [
          "iso" => "ET",
          "name_caps" => "ETHIOPIA",
          "name" => "Ethiopia",
          "iso3" => "ETH",
          "numcode" => 231,
          "phonecode" => 251,
        ],
        [
          "iso" => "FK",
          "name_caps" => "FALKLAND ISLANDS (MALVINAS)",
          "name" => "Falkland Islands (Malvinas)",
          "iso3" => "FLK",
          "numcode" => 238,
          "phonecode" => 500,
        ],
        [
          "iso" => "FO",
          "name_caps" => "FAROE ISLANDS",
          "name" => "Faroe Islands",
          "iso3" => "FRO",
          "numcode" => 234,
          "phonecode" => 298,
        ],
        [
          "iso" => "FJ",
          "name_caps" => "FIJI",
          "name" => "Fiji",
          "iso3" => "FJI",
          "numcode" => 242,
          "phonecode" => 679,
        ],
        [
          "iso" => "FI",
          "name_caps" => "FINLAND",
          "name" => "Finland",
          "iso3" => "FIN",
          "numcode" => 246,
          "phonecode" => 358,
        ],
        [
          "iso" => "FR",
          "name_caps" => "FRANCE",
          "name" => "France",
          "iso3" => "FRA",
          "numcode" => 250,
          "phonecode" => 33,
        ],
        [
          "iso" => "GF",
          "name_caps" => "FRENCH GUIANA",
          "name" => "French Guiana",
          "iso3" => "GUF",
          "numcode" => 254,
          "phonecode" => 594,
        ],
        [
          "iso" => "PF",
          "name_caps" => "FRENCH POLYNESIA",
          "name" => "French Polynesia",
          "iso3" => "PYF",
          "numcode" => 258,
          "phonecode" => 689,
        ],
        [
          "iso" => "TF",
          "name_caps" => "FRENCH SOUTHERN TERRITORIES",
          "name" => "French Southern Territories",
          "iso3" => null,
          "numcode" => null,
          "phonecode" => 0,
        ],
        [
          "iso" => "GA",
          "name_caps" => "GABON",
          "name" => "Gabon",
          "iso3" => "GAB",
          "numcode" => 266,
          "phonecode" => 241,
        ],
        [
          "iso" => "GM",
          "name_caps" => "GAMBIA",
          "name" => "Gambia",
          "iso3" => "GMB",
          "numcode" => 270,
          "phonecode" => 220,
        ],
        [
          "iso" => "GE",
          "name_caps" => "GEORGIA",
          "name" => "Georgia",
          "iso3" => "GEO",
          "numcode" => 268,
          "phonecode" => 995,
        ],
        [
          "iso" => "DE",
          "name_caps" => "GERMANY",
          "name" => "Germany",
          "iso3" => "DEU",
          "numcode" => 276,
          "phonecode" => 49,
        ],
        [
          "iso" => "GH",
          "name_caps" => "GHANA",
          "name" => "Ghana",
          "iso3" => "GHA",
          "numcode" => 288,
          "phonecode" => 233,
        ],
        [
          "iso" => "GI",
          "name_caps" => "GIBRALTAR",
          "name" => "Gibraltar",
          "iso3" => "GIB",
          "numcode" => 292,
          "phonecode" => 350,
        ],
        [
          "iso" => "GR",
          "name_caps" => "GREECE",
          "name" => "Greece",
          "iso3" => "GRC",
          "numcode" => 300,
          "phonecode" => 30,
        ],
        [
          "iso" => "GL",
          "name_caps" => "GREENLAND",
          "name" => "Greenland",
          "iso3" => "GRL",
          "numcode" => 304,
          "phonecode" => 299,
        ],
        [
          "iso" => "GD",
          "name_caps" => "GRENADA",
          "name" => "Grenada",
          "iso3" => "GRD",
          "numcode" => 308,
          "phonecode" => 1473,
        ],
        [
          "iso" => "GP",
          "name_caps" => "GUADELOUPE",
          "name" => "Guadeloupe",
          "iso3" => "GLP",
          "numcode" => 312,
          "phonecode" => 590,
        ],
        [
          "iso" => "GU",
          "name_caps" => "GUAM",
          "name" => "Guam",
          "iso3" => "GUM",
          "numcode" => 316,
          "phonecode" => 1671,
        ],
        [
          "iso" => "GT",
          "name_caps" => "GUATEMALA",
          "name" => "Guatemala",
          "iso3" => "GTM",
          "numcode" => 320,
          "phonecode" => 502,
        ],
        [
          "iso" => "GN",
          "name_caps" => "GUINEA",
          "name" => "Guinea",
          "iso3" => "GIN",
          "numcode" => 324,
          "phonecode" => 224,
        ],
        [
          "iso" => "GW",
          "name_caps" => "GUINEA-BISSAU",
          "name" => "Guinea-Bissau",
          "iso3" => "GNB",
          "numcode" => 624,
          "phonecode" => 245,
        ],
        [
          "iso" => "GY",
          "name_caps" => "GUYANA",
          "name" => "Guyana",
          "iso3" => "GUY",
          "numcode" => 328,
          "phonecode" => 592,
        ],
        [
          "iso" => "HT",
          "name_caps" => "HAITI",
          "name" => "Haiti",
          "iso3" => "HTI",
          "numcode" => 332,
          "phonecode" => 509,
        ],
        [
          "iso" => "HM",
          "name_caps" => "HEARD ISLAND AND MCDONALD ISLANDS",
          "name" => "Heard Island and Mcdonald Islands",
          "iso3" => null,
          "numcode" => null,
          "phonecode" => 0,
        ],
        [
          "iso" => "VA",
          "name_caps" => "HOLY SEE (VATICAN CITY STATE)",
          "name" => "Holy See (Vatican City State)",
          "iso3" => "VAT",
          "numcode" => 336,
          "phonecode" => 39,
        ],
        [
          "iso" => "HN",
          "name_caps" => "HONDURAS",
          "name" => "Honduras",
          "iso3" => "HND",
          "numcode" => 340,
          "phonecode" => 504,
        ],
        [
          "iso" => "HK",
          "name_caps" => "HONG KONG",
          "name" => "Hong Kong",
          "iso3" => "HKG",
          "numcode" => 344,
          "phonecode" => 852,
        ],
        [
          "iso" => "HU",
          "name_caps" => "HUNGARY",
          "name" => "Hungary",
          "iso3" => "HUN",
          "numcode" => 348,
          "phonecode" => 36,
        ],
        [
          "iso" => "IS",
          "name_caps" => "ICELAND",
          "name" => "Iceland",
          "iso3" => "ISL",
          "numcode" => 352,
          "phonecode" => 354,
        ],
        [
          "iso" => "IN",
          "name_caps" => "INDIA",
          "name" => "India",
          "iso3" => "IND",
          "numcode" => 356,
          "phonecode" => 91,
        ],
        [
          "iso" => "ID",
          "name_caps" => "INDONESIA",
          "name" => "Indonesia",
          "iso3" => "IDN",
          "numcode" => 360,
          "phonecode" => 62,
        ],
        [
          "iso" => "IR",
          "name_caps" => "IRAN, ISLAMIC REPUBLIC OF",
          "name" => "Iran, Islamic Republic of",
          "iso3" => "IRN",
          "numcode" => 364,
          "phonecode" => 98,
        ],
        [
          "iso" => "IQ",
          "name_caps" => "IRAQ",
          "name" => "Iraq",
          "iso3" => "IRQ",
          "numcode" => 368,
          "phonecode" => 964,
        ],
        [
          "iso" => "IE",
          "name_caps" => "IRELAND",
          "name" => "Ireland",
          "iso3" => "IRL",
          "numcode" => 372,
          "phonecode" => 353,
        ],
        [
          "iso" => "IL",
          "name_caps" => "ISRAEL",
          "name" => "Israel",
          "iso3" => "ISR",
          "numcode" => 376,
          "phonecode" => 972,
        ],
        [
          "iso" => "IT",
          "name_caps" => "ITALY",
          "name" => "Italy",
          "iso3" => "ITA",
          "numcode" => 380,
          "phonecode" => 39,
        ],
        [
          "iso" => "JM",
          "name_caps" => "JAMAICA",
          "name" => "Jamaica",
          "iso3" => "JAM",
          "numcode" => 388,
          "phonecode" => 1876,
        ],
        [
          "iso" => "JP",
          "name_caps" => "JAPAN",
          "name" => "Japan",
          "iso3" => "JPN",
          "numcode" => 392,
          "phonecode" => 81,
        ],
        [
          "iso" => "JO",
          "name_caps" => "JORDAN",
          "name" => "Jordan",
          "iso3" => "JOR",
          "numcode" => 400,
          "phonecode" => 962,
        ],
        [
          "iso" => "KZ",
          "name_caps" => "KAZAKHSTAN",
          "name" => "Kazakhstan",
          "iso3" => "KAZ",
          "numcode" => 398,
          "phonecode" => 7,
        ],
        [
          "iso" => "KE",
          "name_caps" => "KENYA",
          "name" => "Kenya",
          "iso3" => "KEN",
          "numcode" => 404,
          "phonecode" => 254,
        ],
        [
          "iso" => "KI",
          "name_caps" => "KIRIBATI",
          "name" => "Kiribati",
          "iso3" => "KIR",
          "numcode" => 296,
          "phonecode" => 686,
        ],
        [
          "iso" => "KP",
          "name_caps" => "KOREA, DEMOCRATIC PEOPLE'S REPUBLIC OF",
          "name" => "Korea, Democratic People's Republic of",
          "iso3" => "PRK",
          "numcode" => 408,
          "phonecode" => 850,
        ],
        [
          "iso" => "KR",
          "name_caps" => "KOREA, REPUBLIC OF",
          "name" => "Korea, Republic of",
          "iso3" => "KOR",
          "numcode" => 410,
          "phonecode" => 82,
        ],
        [
          "iso" => "KW",
          "name_caps" => "KUWAIT",
          "name" => "Kuwait",
          "iso3" => "KWT",
          "numcode" => 414,
          "phonecode" => 965,
        ],
        [
          "iso" => "KG",
          "name_caps" => "KYRGYZSTAN",
          "name" => "Kyrgyzstan",
          "iso3" => "KGZ",
          "numcode" => 417,
          "phonecode" => 996,
        ],
        [
          "iso" => "LA",
          "name_caps" => "LAO PEOPLE'S DEMOCRATIC REPUBLIC",
          "name" => "Lao People's Democratic Republic",
          "iso3" => "LAO",
          "numcode" => 418,
          "phonecode" => 856,
        ],
        [
          "iso" => "LV",
          "name_caps" => "LATVIA",
          "name" => "Latvia",
          "iso3" => "LVA",
          "numcode" => 428,
          "phonecode" => 371,
        ],
        [
          "iso" => "LB",
          "name_caps" => "LEBANON",
          "name" => "Lebanon",
          "iso3" => "LBN",
          "numcode" => 422,
          "phonecode" => 961,
        ],
        [
          "iso" => "LS",
          "name_caps" => "LESOTHO",
          "name" => "Lesotho",
          "iso3" => "LSO",
          "numcode" => 426,
          "phonecode" => 266,
        ],
        [
          "iso" => "LR",
          "name_caps" => "LIBERIA",
          "name" => "Liberia",
          "iso3" => "LBR",
          "numcode" => 430,
          "phonecode" => 231,
        ],
        [
          "iso" => "LY",
          "name_caps" => "LIBYAN ARAB JAMAHIRIYA",
          "name" => "Libyan Arab Jamahiriya",
          "iso3" => "LBY",
          "numcode" => 434,
          "phonecode" => 218,
        ],
        [
          "iso" => "LI",
          "name_caps" => "LIECHTENSTEIN",
          "name" => "Liechtenstein",
          "iso3" => "LIE",
          "numcode" => 438,
          "phonecode" => 423,
        ],
        [
          "iso" => "LT",
          "name_caps" => "LITHUANIA",
          "name" => "Lithuania",
          "iso3" => "LTU",
          "numcode" => 440,
          "phonecode" => 370,
        ],
        [
          "iso" => "LU",
          "name_caps" => "LUXEMBOURG",
          "name" => "Luxembourg",
          "iso3" => "LUX",
          "numcode" => 442,
          "phonecode" => 352,
        ],
        [
          "iso" => "MO",
          "name_caps" => "MACAO",
          "name" => "Macao",
          "iso3" => "MAC",
          "numcode" => 446,
          "phonecode" => 853,
        ],
        [
          "iso" => "MK",
          "name_caps" => "MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF",
          "name" => "Macedonia, the Former Yugoslav Republic of",
          "iso3" => "MKD",
          "numcode" => 807,
          "phonecode" => 389,
        ],
        [
          "iso" => "MG",
          "name_caps" => "MADAGASCAR",
          "name" => "Madagascar",
          "iso3" => "MDG",
          "numcode" => 450,
          "phonecode" => 261,
        ],
        [
          "iso" => "MW",
          "name_caps" => "MALAWI",
          "name" => "Malawi",
          "iso3" => "MWI",
          "numcode" => 454,
          "phonecode" => 265,
        ],
        [
          "iso" => "MY",
          "name_caps" => "MALAYSIA",
          "name" => "Malaysia",
          "iso3" => "MYS",
          "numcode" => 458,
          "phonecode" => 60,
        ],
        [
          "iso" => "MV",
          "name_caps" => "MALDIVES",
          "name" => "Maldives",
          "iso3" => "MDV",
          "numcode" => 462,
          "phonecode" => 960,
        ],
        [
          "iso" => "ML",
          "name_caps" => "MALI",
          "name" => "Mali",
          "iso3" => "MLI",
          "numcode" => 466,
          "phonecode" => 223,
        ],
        [
          "iso" => "MT",
          "name_caps" => "MALTA",
          "name" => "Malta",
          "iso3" => "MLT",
          "numcode" => 470,
          "phonecode" => 356,
        ],
        [
          "iso" => "MH",
          "name_caps" => "MARSHALL ISLANDS",
          "name" => "Marshall Islands",
          "iso3" => "MHL",
          "numcode" => 584,
          "phonecode" => 692,
        ],
        [
          "iso" => "MQ",
          "name_caps" => "MARTINIQUE",
          "name" => "Martinique",
          "iso3" => "MTQ",
          "numcode" => 474,
          "phonecode" => 596,
        ],
        [
          "iso" => "MR",
          "name_caps" => "MAURITANIA",
          "name" => "Mauritania",
          "iso3" => "MRT",
          "numcode" => 478,
          "phonecode" => 222,
        ],
        [
          "iso" => "MU",
          "name_caps" => "MAURITIUS",
          "name" => "Mauritius",
          "iso3" => "MUS",
          "numcode" => 480,
          "phonecode" => 230,
        ],
        [
          "iso" => "YT",
          "name_caps" => "MAYOTTE",
          "name" => "Mayotte",
          "iso3" => null,
          "numcode" => null,
          "phonecode" => 269,
        ],
        [
          "iso" => "MX",
          "name_caps" => "MEXICO",
          "name" => "Mexico",
          "iso3" => "MEX",
          "numcode" => 484,
          "phonecode" => 52,
        ],
        [
          "iso" => "FM",
          "name_caps" => "MICRONESIA, FEDERATED STATES OF",
          "name" => "Micronesia, Federated States of",
          "iso3" => "FSM",
          "numcode" => 583,
          "phonecode" => 691,
        ],
        [
          "iso" => "MD",
          "name_caps" => "MOLDOVA, REPUBLIC OF",
          "name" => "Moldova, Republic of",
          "iso3" => "MDA",
          "numcode" => 498,
          "phonecode" => 373,
        ],
        [
          "iso" => "MC",
          "name_caps" => "MONACO",
          "name" => "Monaco",
          "iso3" => "MCO",
          "numcode" => 492,
          "phonecode" => 377,
        ],
        [
          "iso" => "MN",
          "name_caps" => "MONGOLIA",
          "name" => "Mongolia",
          "iso3" => "MNG",
          "numcode" => 496,
          "phonecode" => 976,
        ],
        [
          "iso" => "MS",
          "name_caps" => "MONTSERRAT",
          "name" => "Montserrat",
          "iso3" => "MSR",
          "numcode" => 500,
          "phonecode" => 1664,
        ],
        [
          "iso" => "MA",
          "name_caps" => "MOROCCO",
          "name" => "Morocco",
          "iso3" => "MAR",
          "numcode" => 504,
          "phonecode" => 212,
        ],
        [
          "iso" => "MZ",
          "name_caps" => "MOZAMBIQUE",
          "name" => "Mozambique",
          "iso3" => "MOZ",
          "numcode" => 508,
          "phonecode" => 258,
        ],
        [
          "iso" => "MM",
          "name_caps" => "MYANMAR",
          "name" => "Myanmar",
          "iso3" => "MMR",
          "numcode" => 104,
          "phonecode" => 95,
        ],
        [
          "iso" => "NA",
          "name_caps" => "NAMIBIA",
          "name" => "Namibia",
          "iso3" => "NAM",
          "numcode" => 516,
          "phonecode" => 264,
        ],
        [
          "iso" => "NR",
          "name_caps" => "NAURU",
          "name" => "Nauru",
          "iso3" => "NRU",
          "numcode" => 520,
          "phonecode" => 674,
        ],
        [
          "iso" => "NP",
          "name_caps" => "NEPAL",
          "name" => "Nepal",
          "iso3" => "NPL",
          "numcode" => 524,
          "phonecode" => 977,
        ],
        [
          "iso" => "NL",
          "name_caps" => "NETHERLANDS",
          "name" => "Netherlands",
          "iso3" => "NLD",
          "numcode" => 528,
          "phonecode" => 31,
        ],
    [
          "iso" => "AN",
          "name_caps" => "NETHERLANDS ANTILLES",
          "name" => "Netherlands Antilles",
          "iso3" => "ANT",
          "numcode" => 530,
          "phonecode" => 599,
        ],
        [
          "iso" => "NC",
          "name_caps" => "NEW CALEDONIA",
          "name" => "New Caledonia",
          "iso3" => "NCL",
          "numcode" => 540,
          "phonecode" => 687,
        ],
        [
          "iso" => "NZ",
          "name_caps" => "NEW ZEALAND",
          "name" => "New Zealand",
          "iso3" => "NZL",
          "numcode" => 554,
          "phonecode" => 64,
        ],
        [
          "iso" => "NI",
          "name_caps" => "NICARAGUA",
          "name" => "Nicaragua",
          "iso3" => "NIC",
          "numcode" => 558,
          "phonecode" => 505,
        ],
        [
          "iso" => "NE",
          "name_caps" => "NIGER",
          "name" => "Niger",
          "iso3" => "NER",
          "numcode" => 562,
          "phonecode" => 227,
        ],
        [
          "iso" => "NG",
          "name_caps" => "NIGERIA",
          "name" => "Nigeria",
          "iso3" => "NGA",
          "numcode" => 566,
          "phonecode" => 234,
        ],
        [
          "iso" => "NU",
          "name_caps" => "NIUE",
          "name" => "Niue",
          "iso3" => "NIU",
          "numcode" => 570,
          "phonecode" => 683,
        ],
        [
          "iso" => "NF",
          "name_caps" => "NORFOLK ISLAND",
          "name" => "Norfolk Island",
          "iso3" => "NFK",
          "numcode" => 574,
          "phonecode" => 672,
        ],
        [
          "iso" => "MP",
          "name_caps" => "NORTHERN MARIANA ISLANDS",
          "name" => "Northern Mariana Islands",
          "iso3" => "MNP",
          "numcode" => 580,
          "phonecode" => 1670,
        ],
        [
          "iso" => "NO",
          "name_caps" => "NORWAY",
          "name" => "Norway",
          "iso3" => "NOR",
          "numcode" => 578,
          "phonecode" => 47,
        ],
        [
          "iso" => "OM",
          "name_caps" => "OMAN",
          "name" => "Oman",
          "iso3" => "OMN",
          "numcode" => 512,
          "phonecode" => 968,
        ],
        [
          "iso" => "PK",
          "name_caps" => "PAKISTAN",
          "name" => "Pakistan",
          "iso3" => "PAK",
          "numcode" => 586,
          "phonecode" => 92,
        ],
        [
          "iso" => "PW",
          "name_caps" => "PALAU",
          "name" => "Palau",
          "iso3" => "PLW",
          "numcode" => 585,
          "phonecode" => 680,
        ],
        [
          "iso" => "PS",
          "name_caps" => "PALESTINIAN TERRITORY, OCCUPIED",
          "name" => "Palestinian Territory, Occupied",
          "iso3" => null,
          "numcode" => null,
          "phonecode" => 970,
        ],
        [
          "iso" => "PA",
          "name_caps" => "PANAMA",
          "name" => "Panama",
          "iso3" => "PAN",
          "numcode" => 591,
          "phonecode" => 507,
        ],
        [
          "iso" => "PG",
          "name_caps" => "PAPUA NEW GUINEA",
          "name" => "Papua New Guinea",
          "iso3" => "PNG",
          "numcode" => 598,
          "phonecode" => 675,
        ],
        [
          "iso" => "PY",
          "name_caps" => "PARAGUAY",
          "name" => "Paraguay",
          "iso3" => "PRY",
          "numcode" => 600,
          "phonecode" => 595,
        ],
        [
          "iso" => "PE",
          "name_caps" => "PERU",
          "name" => "Peru",
          "iso3" => "PER",
          "numcode" => 604,
          "phonecode" => 51,
        ],
        [
          "iso" => "PH",
          "name_caps" => "PHILIPPINES",
          "name" => "Philippines",
          "iso3" => "PHL",
          "numcode" => 608,
          "phonecode" => 63,
        ],
        [
          "iso" => "PN",
          "name_caps" => "PITCAIRN",
          "name" => "Pitcairn",
          "iso3" => "PCN",
          "numcode" => 612,
          "phonecode" => 0,
        ],
        [
          "iso" => "PL",
          "name_caps" => "POLAND",
          "name" => "Poland",
          "iso3" => "POL",
          "numcode" => 616,
          "phonecode" => 48,
        ],
        [
          "iso" => "PT",
          "name_caps" => "PORTUGAL",
          "name" => "Portugal",
          "iso3" => "PRT",
          "numcode" => 620,
          "phonecode" => 351,
        ],
        [
          "iso" => "PR",
          "name_caps" => "PUERTO RICO",
          "name" => "Puerto Rico",
          "iso3" => "PRI",
          "numcode" => 630,
          "phonecode" => 1787,
        ],
        [
          "iso" => "QA",
          "name_caps" => "QATAR",
          "name" => "Qatar",
          "iso3" => "QAT",
          "numcode" => 634,
          "phonecode" => 974,
        ],
        [
          "iso" => "RE",
          "name_caps" => "REUNION",
          "name" => "Reunion",
          "iso3" => "REU",
          "numcode" => 638,
          "phonecode" => 262,
        ],
        [
          "iso" => "RO",
          "name_caps" => "ROMANIA",
          "name" => "Romania",
          "iso3" => "ROM",
          "numcode" => 642,
          "phonecode" => 40,
        ],
        [
          "iso" => "RU",
          "name_caps" => "RUSSIAN FEDERATION",
          "name" => "Russian Federation",
          "iso3" => "RUS",
          "numcode" => 643,
          "phonecode" => 70,
        ],
        [
          "iso" => "RW",
          "name_caps" => "RWANDA",
          "name" => "Rwanda",
          "iso3" => "RWA",
          "numcode" => 646,
          "phonecode" => 250,
        ],
        [
          "iso" => "SH",
          "name_caps" => "SAINT HELENA",
          "name" => "Saint Helena",
          "iso3" => "SHN",
          "numcode" => 654,
          "phonecode" => 290,
        ],
        [
          "iso" => "KN",
          "name_caps" => "SAINT KITTS AND NEVIS",
          "name" => "Saint Kitts and Nevis",
          "iso3" => "KNA",
          "numcode" => 659,
          "phonecode" => 1869,
        ],
        [
          "iso" => "LC",
          "name_caps" => "SAINT LUCIA",
          "name" => "Saint Lucia",
          "iso3" => "LCA",
          "numcode" => 662,
          "phonecode" => 1758,
        ],
        [
          "iso" => "PM",
          "name_caps" => "SAINT PIERRE AND MIQUELON",
          "name" => "Saint Pierre and Miquelon",
          "iso3" => "SPM",
          "numcode" => 666,
          "phonecode" => 508,
        ],
        [
          "iso" => "VC",
          "name_caps" => "SAINT VINCENT AND THE GRENADINES",
          "name" => "Saint Vincent and the Grenadines",
          "iso3" => "VCT",
          "numcode" => 670,
          "phonecode" => 1784,
        ],
        [
          "iso" => "WS",
          "name_caps" => "SAMOA",
          "name" => "Samoa",
          "iso3" => "WSM",
          "numcode" => 882,
          "phonecode" => 684,
        ],
        [
          "iso" => "SM",
          "name_caps" => "SAN MARINO",
          "name" => "San Marino",
          "iso3" => "SMR",
          "numcode" => 674,
          "phonecode" => 378,
        ],
        [
          "iso" => "ST",
          "name_caps" => "SAO TOME AND PRINCIPE",
          "name" => "Sao Tome and Principe",
          "iso3" => "STP",
          "numcode" => 678,
          "phonecode" => 239,
        ],
        [
          "iso" => "SA",
          "name_caps" => "SAUDI ARABIA",
          "name" => "Saudi Arabia",
          "iso3" => "SAU",
          "numcode" => 682,
          "phonecode" => 966,
        ],
        [
          "iso" => "SN",
          "name_caps" => "SENEGAL",
          "name" => "Senegal",
          "iso3" => "SEN",
          "numcode" => 686,
          "phonecode" => 221,
        ],
        [
          "iso" => "CS",
          "name_caps" => "SERBIA AND MONTENEGRO",
          "name" => "Serbia and Montenegro",
          "iso3" => null,
          "numcode" => null,
          "phonecode" => 381,
        ],
        [
          "iso" => "SC",
          "name_caps" => "SEYCHELLES",
          "name" => "Seychelles",
          "iso3" => "SYC",
          "numcode" => 690,
          "phonecode" => 248,
        ],
        [
          "iso" => "SL",
          "name_caps" => "SIERRA LEONE",
          "name" => "Sierra Leone",
          "iso3" => "SLE",
          "numcode" => 694,
          "phonecode" => 232,
        ],
        [
          "iso" => "SG",
          "name_caps" => "SINGAPORE",
          "name" => "Singapore",
          "iso3" => "SGP",
          "numcode" => 702,
          "phonecode" => 65,
        ],
        [
          "iso" => "SK",
          "name_caps" => "SLOVAKIA",
          "name" => "Slovakia",
          "iso3" => "SVK",
          "numcode" => 703,
          "phonecode" => 421,
        ],
        [
          "iso" => "SI",
          "name_caps" => "SLOVENIA",
          "name" => "Slovenia",
          "iso3" => "SVN",
          "numcode" => 705,
          "phonecode" => 386,
        ],
        [
          "iso" => "SB",
          "name_caps" => "SOLOMON ISLANDS",
          "name" => "Solomon Islands",
          "iso3" => "SLB",
          "numcode" => 90,
          "phonecode" => 677,
        ],
        [
          "iso" => "SO",
          "name_caps" => "SOMALIA",
          "name" => "Somalia",
          "iso3" => "SOM",
          "numcode" => 706,
          "phonecode" => 252,
        ],
        [
          "iso" => "ZA",
          "name_caps" => "SOUTH AFRICA",
          "name" => "South Africa",
          "iso3" => "ZAF",
          "numcode" => 710,
          "phonecode" => 27,
        ],
        [
          "iso" => "GS",
          "name_caps" => "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS",
          "name" => "South Georgia and the South Sandwich Islands",
          "iso3" => null,
          "numcode" => null,
          "phonecode" => 0,
        ],
        [
          "iso" => "ES",
          "name_caps" => "SPAIN",
          "name" => "Spain",
          "iso3" => "ESP",
          "numcode" => 724,
          "phonecode" => 34,
        ],
        [
          "iso" => "LK",
          "name_caps" => "SRI LANKA",
          "name" => "Sri Lanka",
          "iso3" => "LKA",
          "numcode" => 144,
          "phonecode" => 94,
        ],
    [
          "iso" => "SD",
          "name_caps" => "SUDAN",
          "name" => "Sudan",
          "iso3" => "SDN",
          "numcode" => 736,
          "phonecode" => 249,
        ],
        [
          "iso" => "SR",
          "name_caps" => "SURINAME",
          "name" => "Suriname",
          "iso3" => "SUR",
          "numcode" => 740,
          "phonecode" => 597,
        ],
        [
          "iso" => "SJ",
          "name_caps" => "SVALBARD AND JAN MAYEN",
          "name" => "Svalbard and Jan Mayen",
          "iso3" => "SJM",
          "numcode" => 744,
          "phonecode" => 47,
        ],
        [
          "iso" => "SZ",
          "name_caps" => "SWAZILAND",
          "name" => "Swaziland",
          "iso3" => "SWZ",
          "numcode" => 748,
          "phonecode" => 268,
        ],
        [
          "iso" => "SE",
          "name_caps" => "SWEDEN",
          "name" => "Sweden",
          "iso3" => "SWE",
          "numcode" => 752,
          "phonecode" => 46,
        ],
        [
          "iso" => "CH",
          "name_caps" => "SWITZERLAND",
          "name" => "Switzerland",
          "iso3" => "CHE",
          "numcode" => 756,
          "phonecode" => 41,
        ],
        [
          "iso" => "SY",
          "name_caps" => "SYRIAN ARAB REPUBLIC",
          "name" => "Syrian Arab Republic",
          "iso3" => "SYR",
          "numcode" => 760,
          "phonecode" => 963,
        ],
        [
          "iso" => "TW",
          "name_caps" => "TAIWAN, PROVINCE OF CHINA",
          "name" => "Taiwan, Province of China",
          "iso3" => "TWN",
          "numcode" => 158,
          "phonecode" => 886,
        ],
        [
          "iso" => "TJ",
          "name_caps" => "TAJIKISTAN",
          "name" => "Tajikistan",
          "iso3" => "TJK",
          "numcode" => 762,
          "phonecode" => 992,
        ],
        [
          "iso" => "TZ",
          "name_caps" => "TANZANIA, UNITED REPUBLIC OF",
          "name" => "Tanzania, United Republic of",
          "iso3" => "TZA",
          "numcode" => 834,
          "phonecode" => 255,
        ],
        [
          "iso" => "TH",
          "name_caps" => "THAILAND",
          "name" => "Thailand",
          "iso3" => "THA",
          "numcode" => 764,
          "phonecode" => 66,
        ],
        [
          "iso" => "TL",
          "name_caps" => "TIMOR-LESTE",
          "name" => "Timor-Leste",
          "iso3" => null,
          "numcode" => null,
          "phonecode" => 670,
        ],
        [
          "iso" => "TG",
          "name_caps" => "TOGO",
          "name" => "Togo",
          "iso3" => "TGO",
          "numcode" => 768,
          "phonecode" => 228,
        ],
        [
          "iso" => "TK",
          "name_caps" => "TOKELAU",
          "name" => "Tokelau",
          "iso3" => "TKL",
          "numcode" => 772,
          "phonecode" => 690,
        ],
        [
          "iso" => "TO",
          "name_caps" => "TONGA",
          "name" => "Tonga",
          "iso3" => "TON",
          "numcode" => 776,
          "phonecode" => 676,
        ],
        [
          "iso" => "TT",
          "name_caps" => "TRINIDAD AND TOBAGO",
          "name" => "Trinidad and Tobago",
          "iso3" => "TTO",
          "numcode" => 780,
          "phonecode" => 1868,
        ],
        [
          "iso" => "TN",
          "name_caps" => "TUNISIA",
          "name" => "Tunisia",
          "iso3" => "TUN",
          "numcode" => 788,
          "phonecode" => 216,
        ],
        [
          "iso" => "TR",
          "name_caps" => "TURKEY",
          "name" => "Turkey",
          "iso3" => "TUR",
          "numcode" => 792,
          "phonecode" => 90,
        ],
        [
          "iso" => "TM",
          "name_caps" => "TURKMENISTAN",
          "name" => "Turkmenistan",
          "iso3" => "TKM",
          "numcode" => 795,
          "phonecode" => 7370,
        ],
        [
          "iso" => "TC",
          "name_caps" => "TURKS AND CAICOS ISLANDS",
          "name" => "Turks and Caicos Islands",
          "iso3" => "TCA",
          "numcode" => 796,
          "phonecode" => 1649,
        ],
        [
          "iso" => "TV",
          "name_caps" => "TUVALU",
          "name" => "Tuvalu",
          "iso3" => "TUV",
          "numcode" => 798,
          "phonecode" => 688,
        ],
        [
          "iso" => "UG",
          "name_caps" => "UGANDA",
          "name" => "Uganda",
          "iso3" => "UGA",
          "numcode" => 800,
          "phonecode" => 256,
        ],
        [
          "iso" => "UA",
          "name_caps" => "UKRAINE",
          "name" => "Ukraine",
          "iso3" => "UKR",
          "numcode" => 804,
          "phonecode" => 380,
        ],
        [
          "iso" => "AE",
          "name_caps" => "UNITED ARAB EMIRATES",
          "name" => "United Arab Emirates",
          "iso3" => "ARE",
          "numcode" => 784,
          "phonecode" => 971,
        ],
        [
          "iso" => "GB",
          "name_caps" => "UNITED KINGDOM",
          "name" => "United Kingdom",
          "iso3" => "GBR",
          "numcode" => 826,
          "phonecode" => 44,
        ],
        [
          "iso" => "US",
          "name_caps" => "UNITED STATES",
          "name" => "United States",
          "iso3" => "USA",
          "numcode" => 840,
          "phonecode" => 1,
        ],
        [
          "iso" => "UM",
          "name_caps" => "UNITED STATES MINOR OUTLYING ISLANDS",
          "name" => "United States Minor Outlying Islands",
          "iso3" => null,
          "numcode" => null,
          "phonecode" => 1,
        ],
        [
          "iso" => "UY",
          "name_caps" => "URUGUAY",
          "name" => "Uruguay",
          "iso3" => "URY",
          "numcode" => 858,
          "phonecode" => 598,
        ],
        [
          "iso" => "UZ",
          "name_caps" => "UZBEKISTAN",
          "name" => "Uzbekistan",
          "iso3" => "UZB",
          "numcode" => 860,
          "phonecode" => 998,
        ],
        [
          "iso" => "VU",
          "name_caps" => "VANUATU",
          "name" => "Vanuatu",
          "iso3" => "VUT",
          "numcode" => 548,
          "phonecode" => 678,
        ],
        [
          "iso" => "VE",
          "name_caps" => "VENEZUELA",
          "name" => "Venezuela",
          "iso3" => "VEN",
          "numcode" => 862,
          "phonecode" => 58,
        ],
        [
          "iso" => "VN",
          "name_caps" => "VIET NAM",
          "name" => "Viet Nam",
          "iso3" => "VNM",
          "numcode" => 704,
          "phonecode" => 84,
        ],
        [
          "iso" => "VG",
          "name_caps" => "VIRGIN ISLANDS, BRITISH",
          "name" => "Virgin Islands, British",
          "iso3" => "VGB",
          "numcode" => 92,
          "phonecode" => 1284,
        ],
        [
          "iso" => "VI",
          "name_caps" => "VIRGIN ISLANDS, U.S.",
          "name" => "Virgin Islands, U.s.",
          "iso3" => "VIR",
          "numcode" => 850,
          "phonecode" => 1340,
        ],
        [
          "iso" => "WF",
          "name_caps" => "WALLIS AND FUTUNA",
          "name" => "Wallis and Futuna",
          "iso3" => "WLF",
          "numcode" => 876,
          "phonecode" => 681,
        ],
        [
          "iso" => "EH",
          "name_caps" => "WESTERN SAHARA",
          "name" => "Western Sahara",
          "iso3" => "ESH",
          "numcode" => 732,
          "phonecode" => 212,
        ],
        [
          "iso" => "YE",
          "name_caps" => "YEMEN",
          "name" => "Yemen",
          "iso3" => "YEM",
          "numcode" => 887,
          "phonecode" => 967,
        ],
        [
          "iso" => "ZM",
          "name_caps" => "ZAMBIA",
          "name" => "Zambia",
          "iso3" => "ZMB",
          "numcode" => 894,
          "phonecode" => 260,
        ],
        [
          "iso" => "ZW",
          "name_caps" => "ZIMBABWE",
          "name" => "Zimbabwe",
          "iso3" => "ZWE",
          "numcode" => 716,
          "phonecode" => 263,
        ]
      ];
      CountryCodes::insert($countries);
    
   }
}
